version: '3'
  restart: always

services:
  web:
    build: .
    command: java -jar /srv/CVHost-1.0-SNAPSHOT.war
    volumes:
      - /opt/docs:/opt/docs
    ports:
          - "8999:8999"
    restart: always
