version: '2.3'
  restart: always

services:
  web:
    build: .
    command: java -jar -Xmx300m /srv/CVHost-1.0-SNAPSHOT.war
    volumes:
      - /opt/docs:/opt/docs
    ports:
          - "8999:8999"
    restart: always
    mem_limit: 350m
